version: '3'

services:
  api:
    build:
      context: docker/nginx
    volumes:
      - ./api:/app
    ports:
      - "85:80"
    depends_on:
      - php-fpm
    tty: true
    restart: unless-stopped

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./api:/app
    restart: unless-stopped
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-cli:
    build:
      context: docker/php-cli
    tty: true
    volumes:
      - ./api:/app

  postgres:
    image: postgres:16.0-alpine3.17
    restart: unless-stopped
    tty: true
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: database
    ports:
      - "5435:5432"

volumes:
  database-data:
    driver: local